---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install base packages
  ansible.builtin.apt:
    name:
      - git
      - python3-venv
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker.io
      - postgresql-client
    state: present
    force_apt_get: yes
  notify:
    - Restart Docker

- name: Create Docker CLI plugins directory
  file:
    path: /usr/lib/docker/cli-plugins
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Install Docker Compose plugin
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64"
    dest: "/usr/lib/docker/cli-plugins/docker-compose"
    mode: '0755'
    owner: root
    group: root

- name: Create docker-compose symlink for compatibility
  file:
    src: "/usr/lib/docker/cli-plugins/docker-compose"
    dest: "/usr/bin/docker-compose"
    state: link
    force: yes

- name: Reload systemd to pick up new Docker service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Ensure host nginx is stopped and disabled (using containerized nginx)
  service:
    name: nginx
    state: stopped
    enabled: no
  ignore_errors: true
  changed_when: false