---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install base packages
  ansible.builtin.apt:
    name:
      - git
      - python3-venv
      - python3-pip
      - nginx
      - docker.io
      - docker-compose
    state: present
  notify:
    - Restart Docker
    - Reload nginx

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Ensure nginx service is enabled and running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes


