---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install base packages
  ansible.builtin.apt:
    name:
      - git
      - python3-venv
      - python3-pip
      - docker.io
      - docker-compose
      - postgresql-client-common
    state: present
  notify:
    - Restart Docker

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Ensure host nginx is stopped and disabled (using containerized nginx)
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: no


